import { NuqsAdapter } from 'nuqs/adapters/next/app'

import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import ReactQueryProvider from '../lib/providers/ReactQueryProvider';

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Done",
  description: "Generated by Rock_Ai_Dev",
  icons:{
    icon:'/favicon.svg'
  }
};


export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <ReactQueryProvider>

      <NuqsAdapter>
        {children}
      </NuqsAdapter>
        </ReactQueryProvider>
      </body>
    </html>
  );
}
